FROM ghcr.io/lowlighter/metrics@sha256:0a24a23b769873639e7d7d3bebce0aade41ded920f8bfd74650328f4c4967b48

COPY source/plugins/languages/analyzer/recent.mjs /metrics/source/plugins/languages/analyzer/recent.mjs
